SELECT COUNT(*) FROM DEPOSIT_DEPOHIST WHERE DEPOSIT_ID=clientId=1&depositId=2
SELECT _key FROM DEPOSIT_DEPOSIT.Deposit WHERE PERSON_ID=clientId=1
SELECT MAX(BALANCE) from DEPOSIT_DEPOHIST.Operation where DEPOSIT_ID=clientId=1&depositId=2


